export const TERMS = [
  "Port 20",
  "Port 21",
  "Port 22",
  "Port 23",
  "Port 25",
  "Port 49",
  "Port 53",
  "Port 67",
  "Port 68",
  "Port 69",
  "Port 80",
  "Port 110",
  "Port 123",
  "Port 143",
  "Port 161",
  "Port 162",
  "Port 179",
  "Port 1812",
  "Port 1813",
  "Port 443",

  "IP Protocol 1",
  "IP Protocol 6",
  "IP Protocol 17",
  "IP Protocol 47",
  "IP Protocol 50",
  "IP Protocol 51",
  "IP Protocol 89",

  "ACL 1",
  "ACL 10",
  "ACL 99",
  "ACL 100",
  "ACL 101",
  "ACL 199",
  "ACL Range 1-99",
  "ACL Range 100-199",

  "IEEE 802.1D",
  "IEEE 802.1Q",
  "IEEE 802.1W",
  "IEEE 802.3",
  "IEEE 802.11",

  "RFC 1918",

  "IPv4 Prefix 0.0.0.0/0",
  "IPv4 Prefix 10.0.0.0/8",
  "IPv4 Prefix 127.0.0.0/8",
  "IPv4 Prefix 169.254.0.0/16",
  "IPv4 Prefix 172.16.0.0/12",
  "IPv4 Prefix 192.168.0.0/16",
  "IPv4 Prefix 224.0.0.0/4",

  "IPv6 Prefix ::/0",
  "IPv6 Prefix ::1/128",
  "IPv6 Prefix 2000::/3",
  "IPv6 Prefix FE80::/10",
  "IPv6 Prefix FC00::/7",
  "IPv6 Prefix FD00::/8",
  "IPv6 Prefix FF00::/8",

  "AD 0",
  "AD 1",
  "AD 90",
  "AD 110",
  "AD 120",

  "Metric",
  "Cost",
  "Administrative Distance",
  "Next Hop",
  "Prefix",
  "Gateway of Last Resort",
  "Longest Prefix Match",
  "0.0.0.0",
  "::/0",
  "Routing Table",
  "Static Route",
  "Default Route",
  "Floating Static",

  "Router",
  "Layer 2 Switch",
  "Layer 3 Switch",
  "Firewall",
  "IPS",
  "Access Point",
  "Controller",
  "Endpoint",
  "Server",
  "PoE",

  "Two-Tier",
  "Three-Tier",
  "Spine-Leaf",
  "WAN",
  "SOHO",
  "On-Premises",
  "Cloud",

  "Single-Mode Fiber",
  "Multimode Fiber",
  "Copper",
  "Half Duplex",
  "Full Duplex",
  "Collision",
  "Duplex Mismatch",
  "Speed Mismatch",

  "TCP",
  "UDP",
  "IPv4",
  "IPv6",
  "Unicast",
  "Anycast",
  "Multicast",
  "EUI-64",

  "SSID",
  "RF",
  "Nonoverlapping Channels",
  "Encryption",

  "Virtualization",
  "Server Virtualization",
  "Containers",
  "VRF",

  "MAC Learning",
  "MAC Aging",
  "Frame Switching",
  "Frame Flooding",
  "MAC Address Table",

  "VLAN",
  "Access Port",
  "Voice VLAN",
  "Default VLAN",
  "InterVLAN Connectivity",
  "Trunk Port",
  "Native VLAN",

  "CDP",
  "LLDP",
  "EtherChannel",
  "LACP",

  "STP",
  "Rapid PVST+",
  "Root Bridge",
  "Root Port",
  "Designated Port",
  "Alternate Port",
  "BPDU",
  "PortFast",
  "Root Guard",
  "Loop Guard",
  "BPDU Filter",
  "BPDU Guard",
  "Priority 32768",
  "Priority 4096",

  "WLC",
  "LAG",
  "Telnet",
  "SSH",
  "HTTP",
  "HTTPS",
  "Console",
  "TACACS+",
  "RADIUS",
  "Cloud Managed",
  "QoS Profile",

  "OSPF",
  "OSPFv2",
  "Neighbor Adjacency",
  "Point-to-Point",
  "Broadcast",
  "Router ID",
  "DR",
  "BDR",
  "ABR",
  "Area 0",
  "LSA",
  "Hello",

  "FHRP",
  "HSRP",
  "VRRP",
  "GLBP",

  "NAT",
  "Inside Source NAT",
  "Static NAT",
  "NAT Pool",
  "NTP",
  "DHCP",
  "DHCP Relay",
  "DHCP Client",
  "DNS",
  "SNMP",
  "Syslog",
  "Facility",
  "Severity Level",
  "Classification",
  "Marking",
  "Queuing",
  "Congestion",
  "Policing",
  "Shaping",

  "Threat",
  "Vulnerability",
  "Exploit",
  "Mitigation",
  "User Awareness",
  "Physical Access Control",
  "Local Password",
  "Multifactor Authentication",
  "Certificate",
  "Biometrics",
  "IPsec",
  "Site-to-Site VPN",
  "Remote Access VPN",
  "ACL",
  "DHCP Snooping",
  "Dynamic ARP Inspection",
  "Port Security",
  "Authentication",
  "Authorization",
  "Accounting",
  "WPA",
  "WPA2",
  "WPA3",
  "WPA2 PSK",

  "Automation",
  "Controller-Based Networking",
  "Traditional Networking",
  "Overlay",
  "Underlay",
  "Fabric",
  "Control Plane",
  "Data Plane",
  "Northbound API",
  "Southbound API",
  "AI",
  "Generative AI",
  "Predictive AI",
  "Machine Learning",
  "REST API",
  "HTTP Verb GET",
  "HTTP Verb POST",
  "HTTP Verb PUT",
  "HTTP Verb DELETE",
  "CRUD",
  "JSON",
  "Ansible",
  "Terraform"
];
